apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafscale.componentName" (dict "root" . "component" "operator") }}
  labels:
{{ include "kafscale.labels" . | indent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
{{ include "kafscale.componentSelectorLabels" (dict "root" . "component" "operator") | indent 6 }}
  template:
    metadata:
      labels:
{{ include "kafscale.componentSelectorLabels" (dict "root" . "component" "operator") | indent 8 }}
{{- with .Values.operator.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ include "kafscale.operatorServiceAccountName" . }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.operator.metrics.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFSCALE_OPERATOR_ETCD_ENDPOINTS
              value: "{{ join "," .Values.operator.etcdEndpoints }}"
            - name: KAFSCALE_OPERATOR_LEADER_KEY
              value: "{{ .Values.operator.leaderKey }}"
          resources:
{{- if .Values.operator.resources }}
{{ toYaml .Values.operator.resources | indent 12 }}
{{- else }}
            {}
{{- end }}
{{- with .Values.operator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.operator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.operator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
