{{- if and .Values.operator.metrics.enabled .Values.operator.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kafscale.componentName" (dict "root" . "component" "operator") }}
  labels:
{{ include "kafscale.labels" . | indent 4 }}
{{- with .Values.operator.metrics.serviceMonitor.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
{{ include "kafscale.componentSelectorLabels" (dict "root" . "component" "operator") | indent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.operator.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.operator.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
